# Generated by Django 3.1.6 on 2021-06-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210613_1809'),
        ('home', '0004_auto_20210613_1652'),
    ]

    operations = [
    ]
