# Generated by Django 3.2.3 on 2021-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='acornonac',
            field=models.CharField(choices=[('ac', 'AC'), ('non-ac', 'NON-AC')], default='non-ac', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
