# Generated by Django 3.2.3 on 2021-06-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210617_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furnishing',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Un-furnished')], default='unfurnished', max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.CharField(choices=[('1bhk', '1-BHK'), ('2bhk', '2-BHK'), ('3bhk', '3-BHK')], default='1bhk', max_length=10),
        ),
    ]
