# Generated by Django 3.2.3 on 2021-06-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210617_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='desc',
            field=models.TextField(default='NA', help_text='Want to write more about your property?', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy',
            field=models.IntegerField(default=0, help_text='Enter occupancy per room'),
        ),
        migrations.AddField(
            model_name='property',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
