# Generated by Django 3.2.3 on 2021-06-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210617_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='acornonac',
            field=models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], default='NON-AC', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Un-furnished', 'Un-furnished')], default='Un-furnished', max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.CharField(choices=[('1-BHK', '1-BHK'), ('2-BHK', '2-BHK'), ('3-BHK', '3-BHK')], default='1-BHK', max_length=10),
        ),
    ]
