# Generated by Django 3.2.3 on 2021-06-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210617_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='acornonac',
            new_name='conditioning',
        ),
        migrations.RemoveField(
            model_name='property',
            name='desc',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='', help_text='Want to write more about your property?', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
