# Generated by Django 3.2.3 on 2021-06-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210622_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='NA', help_text='Want to write more about your property?', max_length=100),
        ),
    ]
